version: '3.0'

services:
  nginx:
    build:
      context: docker/nginx
    volumes:
      - ./:/project
    container_name: parse-nginx
    restart: always
    ports:
      - "85:80"
    command: nginx -g 'daemon off;'

  php-fpm:
    build:
      context: docker/php-fpm
    environment:
      XDEBUG_CONFIG: "remote_host=172.18.18.1 remote_enable=1 remote_autostart=off  remote_port=9008"
      PHP_IDE_CONFIG: "serverName=first"
    volumes:
      - ./:/project
    container_name: parse-php-fpm
    depends_on:
      - database

  php-cli:
    build:
      context: docker/php-cli
    volumes:
      - ./:/project
    command: sleep 10000
    container_name: parse-php-cli

  node-cli:
    container_name: parsenode-cli
    build:
      context: ./docker/node-cli
    volumes:
      - ./:/project


###> doctrine/doctrine-bundle ###
  database:
    container_name: parse-db
    image: mariadb:10.3
    volumes:
      - ./data/db/mysql://var/lib/mysql
    ports:
      - "3356:3306"
    restart: always
    environment:
      - MYSQL_PASSWORD=dev
      - MYSQL_USER=dev
      - MYSQL_DATABASE=dev
      - MARIADB_ROOT_PASSWORD=root
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  database:
###> doctrine/doctrine-bundle ###
